.travis.yml, tox.ini
This will use Tox to just build the package and install it for Python 2.7 and 3.4.
Example setup: https://travis-ci.org/westphahl/adafruit-beaglebone-io-python/
=> Use Travis CI to ensure package can be built with Python 2.7 and 3.4

README.rst, source/event_gpio.c, source/event_gpio.h, test/test_led.py
Resolves issue #89. The built-in LEDs are handled by the LED class driver and have a different /sys/ path than the GPIO pins.
See PyBBIO library for reference:
https://github.com/graycatlabs/PyBBIO/blob/master/bbio/platform/beaglebone/config.py#L44
Issue reported in this Adafruit forum post:
https://forums.adafruit.com/viewtopic.php?f=49&t=51906
=> Add support for on-board LEDs (USR0-USR3)

README.rst
@jwcooper  Simple fix so that the On-Board LEDs example code is formatted correctly in the README
=> Fix format of On-Board LEDs code snippet

test/test_adc.py
@jwcooper I've updated the ADC test to handle Linux 4.1+ kernel.
Tested OK with Linux 4.1.15-ti-rt-r43:
```
debian@beaglebone:~/adafruit-beaglebone-io-python/test$ uname -a
Linux beaglebone 4.1.15-ti-rt-r43 #1 SMP PREEMPT RT Thu Jan 21 20:13:58 UTC 2016 armv7l GNU/Linux
debian@beaglebone:~/adafruit-beaglebone-io-python/test$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie
debian@beaglebone:~/adafruit-beaglebone-io-python/test$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-01-24
py ian@beaglebone:~/adafruit-beaglebone-io-python/test$ sudo py.test ./test_adc.p
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.9.2, …
```
=> Update ADC test to handle Linux 4.1+ kernel

source/c_pwm.c
@Dark-Guan reported an issue in [this comment](https://github.com/adafruit/adafruit-beaglebone-io-python/pull/108#issuecomment-242333019) for PR #108 after it was merged:
> I use Linux kamikaze 4.1.6-bone15 Tue Aug 18 12:45:47 UTC 2015 armv7l GNU/Linux
> 
> File "testHardPwm.py", line 6, in 
> PWM.start("P9_14", 50 , 2000, 1)
> RuntimeError: Problem with a sysfs file
> 
> When I run testing demo, the error I get above.
> It's nice that if some body can tell me the problem,thanks!
@MatthewWest worked with @Dark-Guan to [identify the issue and develop a fix](https://github.com/adafruit/adafruit-beaglebone-io-python/pull/108#issuecomment-243331052):
> The invalid argument when setting the duty cycle happens when the duty cycle is set to longer than the period of the pwm. This was happening …
=> Read current duty_ns and pwm_ns before setting default values

Makefile, setup.py, source/c_pwm.c, source/common.c, source/event_gpio.c, source/spimodule.c
Added '-Wall', '-Werror' to compiler flags and fixed compilation errors for python2 and python3.
=> Treat warnings as errors

source/py_adc.c
BBB has 12‐bit ADCs (2^12 = 4,096), meaning a value between 0 and 2^12 − 1 (0 to 4,095), read() should return the raw value divided by 4095, not by 1800.
=> ADC.read() returns wrong value

source/event_gpio.c, source/py_gpio.c
Hi, I have no idea if you're interested in this change but I had real problems with the GPIO.setup() program not working for regular user accounts.  This should be a cleaner fix for issue #36 & #64 rather than just spinning a countdown loop after you export the gpio pin.
If you set your udev rules correctly, it takes around 20-30ms for the permissions to kick in.  If you add a "delay=50" parameter to the GPIO.setup() function, it gives it enough time to fix permissions, and everything works fine as a regular user.
=> Added a delay parameter for GPIO.setup() for udev permissions

source/c_pwm.c, source/common.c, test/test_pwm_setup.py
Add PWM support for ecap0 (P9_42) and ecap2 (P9_28) as requested in #126
=> Add PWM support for ecap pins

source/event_gpio.c, source/event_gpio.h, test/setup/0001-rename-USR-LED-names-to-test-Adafruit_BBIO-issue-129.patch, test/test_led.py
These changes support alternate labels for the USR LEDs based on the triggers name.  This was requested by an Ubuntu Core user in issue #129.
Normal labels:
* beaglebone:green:usr0
* beaglebone:green:usr1
* beaglebone:green:usr2
* beaglebone:green:usr3
Alternate labels:
* beaglebone:green:heartbeat
* beaglebone:green:mmc0
* beaglebone:green:cpu0
* beaglebone:green:mmc1
I've also refactored the pytest script `test_led.py` to cover this new functionality.
However, the device tree bindings on the [official BeagleBoard.org Debian 8.6 ("Jessie") image](https://beagleboard.org/latest-images) must be changed to test the alternate USR LED label functionality.  I've added a patch for `arch/arm/boot/dts/am335x-bone-common.dtsi ` in `ti-linux-4.4.y` branch of the [`ti-linux-kernel-dev` …
=> Add support for alternate USR LED labels

setup.py
When installing this module on a system with Python 3 which has no or non-utf8 locale variables set installation fails because you’re making use of the open() command in setup.py to pipe in things like README.rst and CHANGELOG.rst. This happens because Python 3 tries loading those files with the default encoding (which happens to be ASCII), and then fails with an UnicodeDecodeError.
Suggestion: Use io.open(), which is available for both Python 2 and 3 and specify the encoding of said files explicitly.
One could argue that this problem is client-sided, but I don’t see any real drawbacks fixing this on your side.
Thanks.
=> Make use of io.open() with explicit file encoding in setup.py

source/common.c
Same application as in #138. The small leak in build_path quickly added up and exhausted all my RAM, causing the linux oom-killer to terminate my process. No behavior change, just bugfix, I think.
=> Fix build_path memory leak

source/event_gpio.c
I have an application where I need to switch GPIO direction many times each second (A bidirectional bus). GPIO.setup calls gpio_export each time, but the interaction with /sys/class/gpio/export would report an error into my system logs each time but the first. This would very quickly exhaust all my HDD space.
My patch uses a lookup table similar event_occured in event_gpio.c  instead of the previos linked list. Only pins that are exported by the GPIO module are unexported. This is the same as before, because such pins would produce an error on the write on /sys/class/gpio/export and hence not be added to the list.
=> Fix duplicate export

source/py_gpio.c
Calling GPIO.wait_for_edge() with only two arguments leads to a latent error that is thrown next time the code hits the C API
My steps to reproduce:
download and install latest image from http://beagleboard.org/latest-images (I used 2017-03-19)
`debian@beaglebone:~$ uname -a`
`Linux beaglebone 4.4.54-ti-r93 #1 SMP Fri Mar 17 13:08:22 UTC 2017 armv7l GNU/Linux`
`debian@beaglebone:~$ cat /etc/dogtag`
`BeagleBoard.org Debian Image 2017-03-19`
`debian@beaglebone:~$ sudo python`
`# snip first time warning #`
`[sudo] password for debian:`
`Python 2.7.9 (default, Aug 13 2016, 17:56:53) `
`[GCC 4.9.2] on linux2`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import Adafruit_BBIO.GPIO as GPIO`
`>>> GPIO.setup('P9_15', GPIO.IN)`
`>>> …
=> fix TypeError: function takes exactly 3 arguments (2 given) from wait_for_edge

source/event_gpio.c
Fixed issue #145 GPIO library doesn't free GPIO file descriptor. File descriptor leak.
Made a little bit refactoring.
=> Fixed issue #145 GPIO library doesn't free GPIO file descriptor. File descriptor leak.

source/common.c
@robertcnelson maintains the BeagleBoard.org Debian images and suggested adding this check to see if u-boot overlays are enabled.
If u-boot overlays are enabled, then device tree overlays should not be loaded with the cape manager by writing to the slots file.  There is currently a kernel bug that causes the write to hang.
Refer to: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays
=> Check if u-boot overlays are enabled

source/c_adc.c
Add a delay of 1 second after loading the ADC overlay and that seems to have resolved the issue. The script does now run OK at bootup.
For issue #127
=> Sleep after loading ADC overlay to allow driver load

source/c_pinmux.c, source/py_gpio.c
I added error handling for the gpio.setup() method in the part where it sets up the pinmux mode. Before it just silently failed if it was unable to write to the corresponding sysfs file.
I also altered underlying set_pin_mode() C function to provide debug output (as it is done in other places) when library is built/run in debug mode
=> Error handling for setting up pinmux mode in gpio.setup()

source/common.c, source/event_gpio.c, source/event_gpio.h, source/examples/python/blinkLEDs.py, source/examples/python/button.py, source/examples/python/leds.py
Now the battery level and WIFI LEDs can be blinked.  Added blinkLEDs.py to blink all the built in LEDs.
I increased the sleep between exporting a pin and setting the direction to 200ms since 100ms sometimes failed.  It's still a hack, but it works.
--Mark
=> Added BAT25, BAT50, BAT75, BAT100 and WIFI LEDs

source/c_pinmux.c, source/c_pwm.c, source/common.c, source/common.h, source/event_gpio.c, source/py_gpio.c, source/py_pwm.c, test/issue178.py
Fix GPIO regression caused by the support for the additional BeagleBone Blue built-in LEDs.  Refer to issue #178.
```
debian@beaglebone:~/ssh/adafruit-beaglebone-io-python/test$ sudo /opt/scripts/tools/version.sh
git:/opt/scripts/:[6c2688b0be448b7bb9ca18849b430d496a84acb4]
eeprom:[A335BNLT000C3014BBBK1316]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[BeagleBoard.org Debian Image 2017-10-17]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2017.09-00002-g0f3f1c7907]
bootloader:[eMMC-(default)]:[/dev/mmcblk1]:[U-Boot 2017.09-rc2-00002-g84a7f2]
kernel:[4.9.57-ti-r71]
nodejs:[v6.11.4]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-4-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1] …
```
=> Fix GPIO regression from BeagleBone Blue support

source/c_pwm.c, source/event_gpio.c, test/issue170-pwm.py
For issue #170.
Commit 8e08a40f1411378e60e942b4efeb24984203dd50 moved `pwm_set_polarity()` after `pwm_set_frequency()` and `pwm_set_duty_cycle()`.  `PWM.start()` now runs OK after reboot.
Output from running test:
```   
debian@beaglebone:~/ssh/adafruit-beaglebone-io-python$ sudo python test/issue170-pwm.py; journalctl -p debug -t python --since "1 min ago"
-- Logs begin at Tue 2017-10-31 06:56:00 UTC, end at Tue 2017-10-31 07:36:39 UTC. --
Oct 31 07:35:57 beaglebone python[1997]: Adafruit_BBIO: version <unknown> initialized
Oct 31 07:35:57 beaglebone python[1997]: Adafruit_BBIO: pwm_start: P9_14, 50.000000, 2000.000000, 1
Oct 31 07:35:57 beaglebone python[1997]: Adafruit_BBIO: lookup_exported_pwm: couldn't find 'P9_14'
Oct 31 07:35:57 beaglebone python[1997]: Adafruit_BBIO: …
```
=> Fix polarity error in PWM.setup() for Linux 4.9

Adafruit_BBIO/Encoder.py, Adafruit_BBIO/README.md
Add logging support to the Encoder module and turn off unconditional debug output. To use, add the following statements to any application that uses the module:
```
import logging
logging.basicConfig(level=logging.INFO)
```
To see more verbose output, `logging.DEBUG` can be used. Refer to the [Python logging module documentation](https://docs.python.org/2/library/logging.html) for more info.
The module was also lightly cleaned up by moving the instructions to set up QEP to a separate README.md file for an easier read and maintenance.
=> Encoder: add logging, move docs to README.md

Adafruit_BBIO/Encoder.py
Currently, upon instantiating the `RotaryEncoder` class, a channel index can be given to initialize and use a particular eQEP channel.
On initializing the class however, _all_ possibe channels are configured as qep, regardless of whether they are available or not. That is, the channel index is ignored and _all_ channels are configured instead of just the given one.
This poses a few issues:
- All QEP-enabled pins are inadvertently configured as ` qep`, overriding their global setting, or their configuration in other parts of the code
- Even if a pin is not exposed, the `RotaryEncoder` class will try to initialize it, resulting in an error
- If both the eQEP2 and eQEP2b channels are available, they are also both configured in sequence. Given that they are mutually exclusive, if eQEP2 is …
=> Encoder: initialize only the given channel

Adafruit_BBIO/Encoder.py
- Added a check for kernels >= 4.4
- Cleaned up formatting for the module to be PEP8-compliant
While the diff is quite big, the change is minimal (added kernel check). I've changed all indentations to 4 spaces, removed trailing whitespace, etc. to make the module PEP8-compliant. I thought it had to be done before further additions to the module, so now is probably a good time as any :)
To double-check no further changes were introduced, the diff can be done with an external tool filtering out the whitespace changes.
=> Encoder: do kernel check, PEP8 cleanup

Adafruit_BBIO/Encoder.py
This change fixes the logic for checking if the kernel version is >= 4.4.x to use the Encoder module.
Previously the check would fail for kernels > 4.4.x.
Another alternative implementation would be to use [`LooseVersion` from `distutils.version`](https://stackoverflow.com/a/11887885/1049318)
=> Encoder: corrected kernel check logic

Adafruit_BBIO/README.md
Minor changes to the Encoder module documentation to make it more obvious how to use `RotaryEncoder`
=> Encoder: improved usage documentation

Adafruit_BBIO/Encoder.py
This change fixes the following:
- Correct calculation of the frequency from period on the property getter
- Cast the string returned from sysfs to int to perform the calculation
- Fix the period variable for logging and debug properties
The change builds upon PR #212 and fixes issue #211
=> Encoder: fix frequency calculation from period

Adafruit_BBIO/README.md
Added a note about the need to log out and log back in for the changes to `eqep` group membership to take effect, having received the feedback from a user who got caught by this.
=> Encoder: README.md: added note about eqep group change

source/event_gpio.c, source/py_gpio.c
There is an old issue with the library which results in SEGFAULT if remove_event_detect() function is called from within the python callback. 
More information can be found here:
https://sourceforge.net/p/raspberry-gpio-python/tickets/136/
https://raspberrypi.stackexchange.com/questions/73791/gpio-callbacks-throw-segmentation-fault
https://stackoverflow.com/questions/35632689/how-to-correctly-remove-interrupt-callback-in-beaglebone-black
http://schlierf.info/raspberry/pi/gpio/python/2016/04/15/RPi.GPIO_SegFault.html
The origin of the problem is the way of handling callbacks - C code stores them in a linked list structure, and, while it correctly removes/inserts new items it doesn't do any sanity checks inside the wrapper that iterates over the list. That results in dereferencing zero …
=> * Fixed  SEGFAULT when calling remove_event_detect() from python callback

docs/GPIO.rst, docs/SPI.rst
Incorporate some changes to the documentation to reflect current code as well as make it more newbie friendly.
=> Documentation updates

source/common.c
Added one additional UART entry for the pocketbeagle board in common.c file.  Confirmed to be working by testing on a pocketbeagle with jumpers on the UART4's TX and RX to talk to itself. 
pocketbeagle UART4 pins:  
P2_05 uart4_rxd
P2_07 uart4_txd
=> UART4 added to Pocketbeagle

source/common.c
=> fixing document locaiton and version as current location dosn't load

source/constants.c, source/constants.h
Building with GCC 10.2.1 fails due linking errors caused by having multiple
definitions of the variables defined in the source/constants.h header file.
Fix this by moving the variables definition to the source/constants.c file,
to avoid the variables to be defined each time that the header is included.
While being there, use a single variable instead of having one for each
object that is added to the module.
=> fix link error due multiple variables definitions

source/c_pwm.c
PWM outputs on P9_28 and P9_42 are part of the ECAP hardware block.  This causes 'ecap' to be in the path instead of 'pwm'.  For example:
`/sys/devices/platform/ocp/48300000.epwmss/48300100.ecap/pwm/pwmchip0/pwm0`
is one character longer than:
`/sys/devices/platform/ocp/48302000.epwmss/48302200.pwm/pwm/pwmchip4/pwm0`
Thus the index in pwm_path must be adjusted for the ecap_path_udev path.  This fixes issue #342
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
- **Describe the scope of your change--i.e. what the change does and what parts
of the code were modified.**  This will help us understand any risks of integrating
the code.
- **Describe any …
=> Fix pwm output for ecap pins P9_28 and P9_42 #342

source/py_gpio.c
- **Describe the scope of your change--i.e. what the change does and what parts
of the code were modified.**  This will help us understand any risks of integrating
the code.
`PyEval_ThreadsInitialized()` and `PyEval_InitThreads()` are deprecated (see https://docs.python.org/3.9/whatsnew/3.9.html#deprecated) and break the build.
This PR adds a version check to ignore these calls if we are compiling with a newer Python version.
- **Describe any known limitations with your change.**  For example if the change
doesn't apply to a supported platform of the library please mention it.
N/A
- **Please run any tests or examples that can exercise your modified code.**  We
strive to not break users of the code and running tests/examples helps with this
process.
N/A
=> Fix compilation for newer versions of Python
